name: Stage

on: [pull_request]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  reqs:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.11.7
          architecture: x64
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Check deps
        run: python src/Nix.py -i
  fly_env:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.11.7
          architecture: x64
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Install fly
        run: curl -L https://fly.io/install.sh | sh
      - name: Check envs
        run: /home/runner/.fly/bin/flyctl config env --access-token $FLY_API_TOKEN | python src/Nix.py -e
