name: TypeCheck

on: [pull_request]

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.11.3
          architecture: x64
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install mypy
        run: pip install mypy
      - name: Run mypy
        run: mypy --strict --disable-error-code no-untyped-call --disable-error-code misc .
